name: Update browserslist

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Everyday

jobs:
  cron:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          save-cache: true
          components: rustfmt # for `cargo codegen`

      - uses: oxc-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - run: pnpm update --prod

      - run: cargo codegen

      - run: cargo test

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        id: cpr
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: Update browserslist
          branch: update
          branch-suffix: timestamp
          title: Update browserslist
          assignees: Boshen
          base: main

      - uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        if: steps.cpr.outputs.pull-request-operation == 'created'
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
