name: Miri

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
      - ".github/workflows/miri.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/miri.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          cache-key: miri
          save-cache: ${{ github.ref_name == 'main' }}

      - uses: oxc-project/setup-node@ab97f03642370d79a7e96dd286bd02a1be40e0ba # v1.3.0

      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup

      # `--lib --bins --tests` omits doctests, which Miri can't run
      # https://github.com/oxc-project/oxc/pull/11092
      - name: Test with Miri
        run: |
          cargo miri test --lib --bins --tests --all-features
        env:
          MIRIFLAGS: -Zmiri-disable-isolation
